---
development:
  cloud_name: siftedwheat
  api_key: '948762216444818'
  api_secret: kTv15OB8lz4vT_yCMPTJycbD5ak
  enhance_image_tag: true
  static_image_support: false
staging:
  cloud_name: siftedwheat
  api_key: '948762216444818'
  api_secret: kTv15OB8lz4vT_yCMPTJycbD5ak
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: siftedwheat
  api_key: '948762216444818'
  api_secret: kTv15OB8lz4vT_yCMPTJycbD5ak
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: siftedwheat
  api_key: '948762216444818'
  api_secret: kTv15OB8lz4vT_yCMPTJycbD5ak
  enhance_image_tag: true
  static_image_support: false